FROM quay.io/kairos/kairos-init:v0.5.20@sha256:d90e8dd3d43f8c90b4cc9f76b1eb7282823737867dfdf5dda88a66c7683bccfc AS kairos-init

FROM almalinux:10@sha256:a81adef1de0ec017d2f483e6acedf6da4c060a93716192c23cac052386e48035 AS base-kairos

ARG KUBERNETES_DISTRO=k3s
# renovate: datasource=custom.k3s depName=k3s
ARG KUBERNETES_VERSION=v1.32.3+k3s1
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG VERSION

COPY --from=kairos-init /kairos-init /kairos-init

# hadolint ignore=DL3059
RUN /kairos-init \
  -s install \
  --fips \
  -k "${KUBERNETES_DISTRO}" \
  --k8sversion "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3041
RUN dnf update && dnf install -y \
  cifs-utils \
  nmstate \
  python3-pip && \
  dnf clean all

# hadolint ignore=DL3013,DL3059
RUN python3 -m pip install --no-cache-dir --target /usr/lib/python3.12/site-packages --upgrade pip

# hadolint ignore=DL3013,DL3059
RUN python3 -m pip install --no-cache-dir --target /usr/lib/python3.12/site-packages \
  packaging \
  requests \
  setuptools \
  wheel

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
  chmod 700 get_helm.sh && \
  HELM_INSTALL_DIR=/usr/bin VERIFY_CHECKSUM=false ./get_helm.sh && \
  rm get_helm.sh

# hadolint ignore=DL3059
RUN /kairos-init \
  -s init \
  --fips \
  -k "${KUBERNETES_DISTRO}" \
  --k8sversion "${KUBERNETES_VERSION}" \
  -l debug \
  -m "${MODEL}" \
  -t "${TRUSTED_BOOT}" \
  --version "${VERSION}"

# hadolint ignore=DL3059
RUN /kairos-init validate -t "${TRUSTED_BOOT}"

# hadolint ignore=DL3059
RUN rm /kairos-init
