---
name: Build and publish

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      max-parallel: 1
      matrix:
        distro:
          - alma9
          - alma10

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tag and kairos version
        id: release-tag
        run: |
          kairos_init_version=$(grep "^FROM quay.io/kairos/kairos-init:" images/Dockerfile.${{ matrix.distro }} | cut -d':' -f2 | awk -F '[@]' '{print $1}')
          k3s_version=$(grep "^ARG KUBERNETES_VERSION=" images/Dockerfile.${{ matrix.distro }} | cut -d'=' -f2)
          alma_major_version=$(grep "^FROM almalinux:" images/Dockerfile.${{ matrix.distro }} | cut -d':' -f2 | awk -F '[@]' '{print $1}')
          tag="${alma_major_version}"-standard-amd64-generic-"${kairos_init_version}"-k3s"${k3s_version}"
          release_tag="${{ github.event.release.tag_name }}"
          echo "tag=${tag//+/-}" >> "$GITHUB_OUTPUT"
          echo "kairos_version=${alma_major_version}.${release_tag//.}" >> "$GITHUB_OUTPUT"

      - name: Extract tags and labels
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ${{ env.REGISTRY }}/ucl-arc/kairos-almalinux

      - name: Build and push image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v5
        with:
          context: .
          file: images/Dockerfile.${{ matrix.distro }}
          push: true
          tags:
            ${{ env.REGISTRY }}/ucl-arc/kairos-almalinux:${{
            steps.release-tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VERSION=${{ steps.release-tag.outputs.kairos_version }}"
